# Generated by Django 3.0.6 on 2020-07-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magical_notepad', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='content',
        ),
    ]
